apiVersion: v1
kind: Service
metadata:
  name: transaction-mysql
  labels:
    app: transaction-service
spec:
  ports:
    - port: 3306
  selector:
    app: transaction-service
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: transaction-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-mysql
  labels:
    app: transaction-service
spec:
  selector:
    matchLabels:
      app: transaction-service
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: transaction-service
        tier: mysql
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          env:
            - name: root
              valueFrom:
                secretKeyRef:
                  name: admin
                  key: admin
          livenessProbe:
            tcpSocket:
              port: 3306
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
