apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce  # claim can be mounted by a single node
  resources:
    requests:
      storage: 5Gi  # storage size required for the PVC